
// ViewRegistry.java
// Andrew Davison, ad@fivedots.coe.psu.ac.th, September 2016

/* View RDB files generated by my regmerge.bat batch file.
      Usage:  run ViewRegistry RandomSents.rdb

   But regview.bat gives more details by using Office's 
   regview.exe tool:
      Usage: regview RandomSents

*/

import com.sun.star.uno.*;
import com.sun.star.lang.*;
import com.sun.star.frame.*;
import com.sun.star.view.*;
import com.sun.star.beans.*;

import com.sun.star.text.*;

import com.sun.star.registry.*;



public class ViewRegistry
{

  public static void main(String args[])
  {
    if (args.length != 1) {
      System.out.println("Usage: ViewRegistry RDB-fnm");
      return;
    }

    Lo.loadOffice();

    XSimpleRegistry reg = Registry.view(args[0]);
    if (reg != null) {
      Registry.print(reg);
      Registry.close(reg);
    }

    Lo.closeOffice();
  } // end of main()


}  // end of ViewRegistry class
